import type { Metadata } from "next";
import { ClientWrapper } from "../components/clientwrapper/index";
import { AuthContextProvider } from "../context/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AuthContextProvider>
          <ClientWrapper>
            {children}
          </ClientWrapper>
        </AuthContextProvider>
      </body>
    </html>
  );
}
